import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import Navbar from "@/components/customcomponents/Navbar";
import { Toaster } from "@/components/ui/toaster";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "QwiksSave | Fintech",
   description: "Generated by create next app",
};

export interface InfoProp {
   author: string;
   user: boolean;
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en" suppressHydrationWarning className="antialiased">
         <body className={nunito.className}>
            <ThemeProvider
               attribute="class"
               defaultTheme="dark"
               enableSystem
               disableTransitionOnChange>
               <Navbar />
               <Toaster />
               {children}
            </ThemeProvider>
         </body>
      </html>
   );
}
